apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "sqldb-pv"
  labels:
    type: local
spec:
  storageClassName: default
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: finance-db
spec:
  template:
    metadata:
      labels:
        app: finance-db
        component: finance-db
    spec:
      containers:
      - name: finance-db
        image: microsoft/mssql-server-linux
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: YOUR_PASSWORD
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: sqldb-home
      volumes:
      - name: sqldb-home
        persistentVolumeClaim:
          claimName: sqldb-pv
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: finance-db
    component: finance-db
  name: finance-db
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 10433
      targetPort: 1433
      name: finance-db-port
  selector:
    app: finance-db
    component: finance-db
